[project]
name = "airbnb-guided-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dbt-core>=1.8.7",
    "dbt-databricks>=1.8.7",
    "sqlfluff>=3.3.1",
]
